# Generated by Django 4.2.20 on 2025-05-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
            preserve_default=False,
        ),
    ]
