# Generated by Django 4.2.20 on 2025-05-10 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_farm_farmer_farm_farmers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
